type Query {
    """
    The paginated list of organizations that a user has access to. Access to an organization
    includes all of its descendants, so returning the top-most accessible organizations is enough.
    Moderne presents the organizations in the order they are returned.
    """
    userOrganizationsPages(
        user: User!
        after: String
        first: Int = 100
        before: String
        last: Int
    ): OrganizationConnection!

    """
    Return a commit message for this repository given an input commit message.

    This is useful for if you need to supply, for example, a ticket number in each commit.
    """
    commitMessage(
        commitInput: CommitInput!
        repository: RepositoryInput!
    ): Commit!
}

input CommitInput {
    message: String!
}

input User {
    email: String!
}

type Organization {
    id: ID!
}

type Commit {
    message: String!
}

type OrganizationConnection {
    edges: [OrganizationEdge]
    pageInfo: PageInfo
}

type OrganizationEdge {
    node: Organization
    cursor: String
}

# Pagination Type - Generic
type PageInfo {
    hasPreviousPage: Boolean!
    hasNextPage: Boolean!
    startCursor: String
    endCursor: String
}

input RepositoryInput {
    path: String!
    origin: String
    branch: String
}
