---
name: ci

on:
  push:
    branches:
      - main
    tags-ignore:
      - "*"
  pull_request:
    branches:
      - main
  workflow_dispatch: {}
  # weekly run to ensure project still builds
  schedule:
    - cron: "0 0 * * 1"

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: moderneinc/gh-automation/.github/workflows/ci-gradle.yml@main
    secrets: inherit
